### ISSUE TITLE
Image Upload Not working 

### ISSUE THREAD

**Issue by darkucfknight** [CRogers18/Movie-TV-Tracker#4]
images aren't uploading with the new code. confirmed its working with old code.

**Comment by bthomason1** [comment]
Hey sorry I've been so mia. Everything is crashing in senior design and we have a demo on Wed. I'll be free Thurs and Fri if I can help out more then? Please forgive me.

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: darkucfknight <notifications@github.com> Date: 10/26/17  6:12 PM  (GMT-05:00) To: CRogers18/Movie-TV-Tracker <Movie-TV-Tracker@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [CRogers18/Movie-TV-Tracker] Image Upload Not working (#4) 
images aren't uploading with the new code. confirmed its working with old code.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CRogers18/Movie-TV-Tracker","title":"CRogers18/Movie-TV-Tracker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CRogers18/Movie-TV-Tracker"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Image Upload Not working  (#4)"}],"action":{"name":"View Issue","url":"https://github.com/CRogers18/Movie-TV-Tracker/issues/4"}}}

**Comment by darkucfknight** [comment]
Fixed! key to fixing this was waiting for the image to fully upload before changing pages. added a progress bar to show the user that the system is working and not just sitting there.
